site_name: House of YuanJQ
theme:
  name: material
  features:
    - navigation.tabs  # 页面顶部导航栏
    - navigation.indexes # 左侧边栏大节点是否可以被导向到 index.md，可以不写，但不能没有
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# 调整导航层级（关键修改）
nav:
  - 主页: index.md   
  - 互助会: 
    - 互助会: mutual_aid_society/index.md
    - 图片故事: mutual_aid_society/picture_story.md
    - 排行榜: mutual_aid_society/rank.md
    - 日记: mutual_aid_society/diary.md
  - 书影音:
    - 书: shuyingyin/book.md
    - 影: shuyingyin/video.md
    - 音: shuyingyin/audio.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # 警告框框配置
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # 图片配置
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  # 同样是 图片配置
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 60%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
