site_name: House of kang
theme:
  name: material
  features:
    - navigation.tabs  # 页面顶部导航栏
    - navigation.indexes # 左侧边栏大节点是否可以被导向到 index.md，可以不写，但不能没有
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# 调整导航层级（关键修改）
nav:
  - 主页: index.md   
  - 花园: 
    - 花园: gonghui/index.md
    - 照片:
      - 毕业: gonghui/graduation.md
    - 排行榜: gonghui/rank.md
  - 书影音:
    - 书: shuyingyin/book.md
    - 影: shuyingyin/video.md
    - 音: shuyingyin/audio.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox:
      touchNavigation: true
      loop: true
